language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

env:
  - QT_SELECT=5

dist: trusty
sudo: required

install:
  - wget https://github.com/aquynh/capstone/archive/3.0.4.tar.gz -O /tmp/capstone.tar.gz
  - tar -xvf /tmp/capstone.tar.gz
  - pushd capstone-3.0.4
  - ./make.sh && sudo ./make.sh install
  - popd
  - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qt5-qmake

script:
  - cargo build --verbose
  - pushd libllama
  - cargo test --verbose
  - popd
  - cargo test --verbose